site:
  title: Документация 
  url: https://StepanovSerg.github.io 
  start_page: component-a::sidebar.adoc 
content:
  sources:
  - url: https://github.com/stepanovserg/demo-docs-component-a.git
    branches: main
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
    snapshot: true
output:
 dir: ./